[build]
  publish = "public"
  functions = "lambda"
  command = "npm run prod"

[[plugins]]
package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'suffix'

[[plugins]]
package = "netlify-plugin-inline-functions-env"